# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20171221_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='request',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='suite_request',
            field=models.TextField(blank=True),
        ),
    ]
