# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20171221_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='case_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='suite_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
