# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-22 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20171221_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='case_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='suite_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='suite_request',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='suite_variables',
            new_name='variables',
        ),
    ]
