# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-26 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20171222_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='extract',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.TestSuite'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='variables',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='variables',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
