# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-26 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20171226_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tester', models.CharField(max_length=50)),
                ('is_del', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_del',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='is_del',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.TestProject'),
        ),
    ]
