# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-11 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20171226_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='case_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='suite_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
