# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-11 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20180111_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='is_del',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='is_del',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='is_del',
            field=models.IntegerField(default=0),
        ),
    ]
